Fallback Authentication Provider
9p4/jellyfin-plugin-sso pull request #9
Opened 2022-02-20 17:25 UTC by Pfuenzle

With this commit, a Fallback Provider can be set in the config via `<DefaultProvider>NAMEOFPROVIDER</DefaultProvider>`.

The set provider then gets assigned to the user after he has been logged in. If it is not set, nothing is changed.

With this, an user can login via SSO but is still able to log in via other providers on a later moment via username/password. This could also be changed to always set the Default Provider to the normal on (using the Jellyfin DB) if needed.

2022-02-21 16:32 UTC, 9p4 requested changes

2022-02-21 16:32 UTC, 9p4 commented on SSO-Auth/Api/SSOController.cs
> +                        if(config.DefaultProvider != "")
This should not be here, and instead should be moved into the `Authenticate` function.

2022-02-21 16:32 UTC, 9p4 commented on SSO-Auth/Api/SSOController.cs
> +                if(config.DefaultProvider != "")
This should not be here, and instead should be moved into the `Authenticate` function.

2022-02-21 17:08 UTC, Pfuenzle commented
I also thought that, but in Authenticate() the "AuthenticateDirect" function gets called on return and I guessed that changing the Auth Provider to something else before that call would interfere with the login process.
But if it doesnt, Ill try to change it

2022-02-21 18:00 UTC, 9p4 commented
I would say to add another parameter to AuthenticateDirect and have the code in one place to prevent duplication.

2022-03-13 19:06 UTC, 9p4 commented
@Pfuenzle any update?

2022-04-07 08:20 UTC, Pfuenzle commented
Works fine now from my testing, sorry it took so long. also all warnings and errors should be gone

2022-04-07 20:12 UTC, 9p4 approved these changes

2022-04-07 20:12 UTC, 9p4 commented
I'm not going to merge the build script because it seems to be specific to your machine.

2022-04-07 20:16 UTC, merged

2022-04-07 21:49 UTC, Pfuenzle commented
Oh yes, I did not mean to include it, that was just for me to build it, missed the file when committing.
Thanks for merging it 👍

2022-04-07 21:52 UTC, 9p4 commented
Thanks for your contribution! Once I get this automated test system running, I'll push out a release.